services:
  - docker

before_install:
  - sudo add-apt-repository ppa:duggan/bats --yes
  - sudo apt-get update -qq
  - sudo apt-get install -qq bats
  - sudo apt-get install -y swi-prolog
  - sudo apt-get install jq

script:
  - bats test

notifications:
  email:
    recipients:
      - will.weiss1230@gmail.com
      - conorwdowling@gmail.com
    on_success: always
    on_failure: always
