#! /usr/bin/env bash

source src/parse_english_syntax_trees/parse_english_syntax_trees.bash
source src/english_syntax_trees_to_prolog_ast.bash
source src/prolog_ast_to_prolog_code.bash
source src/prolog_interpreter.bash

cat "$1" \
  | parse_english_syntax_trees \
  | english_syntax_trees_to_prolog_ast \
  | prolog_ast_to_prolog_code \
  | prolog_interpreter
